./clean.sh
./commands.sh
./a.out
python3 ../../bugDetector/traceFormatter.py output.txt formattedTrace.txt
echo 'Generated the formmated trace file'
echo ''
python3 ../../bugDetector/PTimes.py formattedTrace.txt assertionsOPT.txt
echo 'Generated violations that need to be satisfied. This assertion file can also be generated by a human without running PTimes.py'
echo ''
python3 ../../bugDetector/violationDetector.py formattedTrace.txt assertionsOPT.txt 
echo 'Final assertion violations generated and comprehension written to file.'
echo ''
#The final output i.e the contraint violations are stored 
#in the output file of PTimes which is 'PMConstraintViolations_formattedTrace.txt'
